### ISSUE TITLE
bootstrap does not copy template

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#10]
README Usage says:

> Either you use the default template or modify it. If you choose for the latter you can copy the templates directory...

So if one were using the default by just calling `init` template shall be copy properly, but it isn't. Please consider adding that feature (auto-copy) or changed the README a bit to prevent confusion.

**Comment by ghost** [comment]
Actually template copy should work with this call https://github.com/oceanhouse21/dokker/blob/master/bin/init#L14 to this function https://github.com/oceanhouse21/dokker/blob/master/dokker.js#L419

You say it's broken?

**Comment by kengz** [comment]
Hmm yeah the first time I used it it screamed something along "the folder template not found" and exited so I had to manually copy it.

**Comment by kengz** [comment]
Here is the error log

```
Wahs-MacBook-Pro:Quiver kengz$ ./node_modules/dokker/bin/dokker
docco: /Users/kengz/Google Drive/Quiver/.tmp/index.js -> /Users/kengz/Google Drive/Quiver/docs/annotated/index.html
/Users/kengz/Google Drive/Quiver/node_modules/dokker/node_modules/promise/lib/done.js:10
      throw err;
            ^
Error: ENOENT, open '/Users/kengz/Google Drive/Quiver/templates/index.ejs.html'
    at Error (native)
Wahs-MacBook-Pro:Quiver kengz$ 
```

and yes, the `templates` folder was never copied to the root.

**Comment by ghost** [comment]
You're right. There was a mkdir missing.
