### ISSUE TITLE
feature enhancement: live reload with browserSync

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#11]
This will be a cool come-in-the-box feature: user will not have to set anything up/install anything and just do `watch` for a live reload. Okay this may be a bigger fix that it seems; def not trivial but it'll allow many people to use this feature.

Since your `watch` is out, I've been using it with my own live reload, that is through `gulp` and `browserSync`. However full integration would require changing some structures in `dokker.js`, and letting `gulp` listen to the `promise` returned by dokker once it has written to the `html`.

Without the access to that dokker `promise` now I'm doing it by using some fixed time delay to wait to the file-write to finish.

Let me know what you think and I'll look into it when I'm free.

**Comment by ghost** [comment]
Mmmh. Let me try browsersync in some project first before getting the whole gulp boilerplate.

**Comment by kengz** [comment]
Sure, I got some examples if that helps. Here it is, starting from https://github.com/kengz/lomath/blob/master/gulpfile.js#L211

**Comment by kengz** [comment]
@georgschlenkhoff Hey there I almost got it working but need few inputs for you.
How do you call the methods in `dokker.js`? 
1. I need the command for the following to build then reload browser:

```
gulp.task('build', exec.bind('some build command here'))
// Reloading browserSync
gulp.task('reload', ['build'], reload);
```
1. How are you doing your `bin` folder executables? I can actually export this whole gulp task as a function to be called from your `watch`.

**Comment by ghost** [comment]
@kengz: I guess this is done, right? Let me know if not
