### ISSUE TITLE
Links in html not updated from template

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#12]
in fact, the path to the annotated html is never set in `dokker.js`. It remains as the given `annotated/dokker.html` in the template.
Fixed this issue by changing a line in the template `index.ejs.html`

```
<li><a href="tests.html">Test suite</a></li>
<li><a href=<%= annotatedpath %>>Annotated Source</a></li>
```

and adding a path-adder under the function `injectTemplate` in `dokker.js` line 87:
`annotatedpath: 'annotated/'+options.source`

Finally, with that, the `literate.source` in `.dokker.json` is never used (it was never used anyway), so we can remove it.

I'll submit another pull request for this once the other is accepted. Don't want to clog it up.

**Comment by kengz** [comment]
Extending this issue to include similar problems with the generated html containing old links to dokker.js.

**Comment by ghost** [comment]
Yup, that sounds reasonable to me. Send me PR and I'll merge.

**Comment by kengz** [comment]
Can you close this? I don't have write permission.
