### ISSUE TITLE
We can integrate xplain library

### ISSUE THREAD

**Issue by bahmutov** [oceanhouse21/dokker#4]
https://github.com/bahmutov/xplain

Xplain also generates docs, and also looks at the unit tests, but it can transform unit tests into examples. The framework specific syntax is replaced with human text, for example

``` js
/** @sample add */
QUnit.test('adds numbers', function () {
    QUnit.equal(add(2, 3), 5);
});
```

will be transformed into `add(2, 3); // 5` - that can be inserted into any docs as example.

**Comment by ghost** [comment]
@bahmutov: Thanks for your idea. Looked at your project. Looks interesting!

So what is the specific use case for your module? People using QUnit as test framework?

**Comment by ghost** [comment]
Feel free to fork this project and make a PR if you have some stable feature. I'm closing for now.
