### ISSUE TITLE
Mocha options

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#5]
Please allow specification of Mocha test styles in `.dokker.json` for overriding line 124 of `dokker.js`'s default `exec('mocha --reporter doc...`
For example, some people might use `mocha -u tdd` or `mocha -u bdd`.

**Comment by ghost** [comment]
@kengz: interesting idea. Will check how to do it.

**Comment by kengz** [comment]
I got the fix. Please bear with me for a second and I'll push a fork :)

**Comment by ghost** [comment]
https://github.com/oceanhouse21/dokker/pull/9
