### ISSUE TITLE
The last @param argument is dropped

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#7]
Sorry to bombard you with the issues man, but hey I really love dokker already! Awesome work there.

It seems that the last parameter is always dropped.
Doing this for a function `distributeLeft(fn, X, y)` with

```
/**
   * Distribute fn with left tensor X over right scalar y.
   *
   * @type Function
   * @param {Function} fn - a binary function.
   * @param {Array} X - a tensor.
   * @param {number} y - a scalar.
   * 
   */
```

Outputs `distributeLeft(fn, X)` in the generated doc.
Whereas if I place a sacrificial @param tag like this fixes the problem.

```
/**
   * Distribute fn with left tensor X over right scalar y.
   *
   * @type Function
   * @param {Function} fn - a binary function.
   * @param {Array} X - a tensor.
   * @param {number} y - a scalar.
   * @param sacrificial fix //right here.
   * 
   */
```

outputs  `distributeLeft(fn, X, y)` properly.

**Comment by kengz** [comment]
To clarify, to problem only happens if there's no other tags behind the last @param tag. For example, if a @return follows after the @param, then no sacrificial fix is needed. Hope that helps.

**Comment by ghost** [comment]
@kengz: Thanks man for your heavy contribution. I'm feeling honoured that lover Dokker. So regarding the param drop, please check out if this is a issue with [docdown](https://github.com/jdalton/docdown). Because Dokker is not doing any JSDoc transformations on its own, but heavily relying on docdown for that.

However, your function should always return sth, shouldn't it ;-)

**Comment by kengz** [comment]
Hi, you're right. It's a less-known bug with JSDoc I think; somebody found the same issue [here](https://groups.google.com/forum/#!topic/jsdoc-users/lHQFtFvj4ic). So the fix is to always include some other tag after the last @param.

You may close this :)

**Comment by ghost** [comment]
Alright. Will close. Thx.
