### ISSUE TITLE
feature request: add a `hljs-special` class

### ISSUE THREAD

**Issue by kengz** [oceanhouse21/dokker#8]
It'd be nice to be able to pick out the special characters and give then different colors, like you did with `hljs-number, hljs-string, hljs-comment` etc., so that for example in `_.foo([bar, baz])` the characters `_.([])` can have a different color than the rest.

**Comment by ghost** [comment]
@kengz: That sounds good to me. If you like, just grap the CSS file and just append to [that line](https://github.com/oceanhouse21/dokker/blob/master/templates/styles.css#L361) your CSS idea and I will merge your commit.

**Comment by kengz** [comment]
Hello again. I've customized my own theme and changed more things in the CSS, and added colors to all the `hljs-*` attributes I've generated. I think it's good a have a default theme where these are already well-distinguished. Moreover I regrouped them together for easy editing.

```
.lang-js {
  color: #78dbf9;
}
span.hljs-number {
  color: #d59cf6;
}
span.hljs-string{
  color: #8bdb97;
}
span.hljs-regexp{
  color: #dbad83;
}
span.hljs-literal{
  color: #e26a78;
}
span.hljs-keyword{
  color: #d59cf6;
}
span.hljs-comment {
  color: #99a4c7;
}
span.hljs-special {
  color: #bdc4df;
}
```

Finally, I spent a little time to incorporate some material design and colors into the theme. Here's how it looks like now:
![screen shot 2015-06-23 at 10 10 46 am](https://cloud.githubusercontent.com/assets/8209263/8308059/894b48e8-1990-11e5-9f68-ecb1d6cb638a.png)

Would you like me to push that too? Then you can review it for yourself.

**Comment by ghost** [comment]
https://github.com/oceanhouse21/dokker/pull/9

**Comment by ghost** [comment]
@kengz: Thanks, man! Put you on the list of contributors ;-)
